src/OC/PlatformBundle/Entity/Image.php
<?php

namespace OC\PlatformBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;


/**
 * Image
 *
 * @ORM\Table(name="oc_image")
 * @ORM\Entity(repositoryClass="OC\PlatformBundle\Entity\ImageRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Image
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;
    
    private $file;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     *
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }
    
    
    
    public function getFile()
    {
        return $this->file;
    }
    
    
    
    // On ajoute cet attribut pour y stocker le nom du fichier temporairement
    private $tempFilename;

    // On modifie le setter de File, pour prendre en compte l'upload d'un fichier lorsqu'il en existe déjà un autre
    public function setFile(UploadedFile $file)
    {
        $this->file = $file;

        // On vérifie si on avait déjà un fichier pour cette entité
        if (null !== $this->url) {
          // On sauvegarde l'extension du fichier pour le supprimer plus tard
          $this->tempFilename = $this->url;

          // On réinitialise les valeurs des attributs url et alt
          $this->url = null;
          $this->alt = null;
        }
    }

    /**
    * @ORM\PrePersist()
    * @ORM\PreUpdate()
    */
    public function preUpload()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif)
        if (null === $this->file) {
          return;
        }

        // Le nom du fichier est son id, on doit juste stocker également son extension
        // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
        $this->url = $this->file->guessExtension();

        // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
        $this->alt = $this->file->getClientOriginalName();
    }

    /**
    * @ORM\PostPersist()
    * @ORM\PostUpdate()
    */
    public function upload()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif)
        if (null === $this->file) {
          return;
        }

        // Si on avait un ancien fichier, on le supprime
        if (null !== $this->tempFilename) {
          $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
          if (file_exists($oldFile)) {
            unlink($oldFile);
          }
        }

        // On déplace le fichier envoyé dans le répertoire de notre choix
        $this->file->move(
          $this->getUploadRootDir(), // Le répertoire de destination
          $this->id.'.'.$this->url   // Le nom du fichier à créer, ici « id.extension »
        );
    }

    /**
    * @ORM\PreRemove()
    */
    public function preRemoveUpload()
    {
        // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
        $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
    }

    /**
    * @ORM\PostRemove()
    */
    public function removeUpload()
    {
        // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
        if (file_exists($this->tempFilename)) {
          // On supprime le fichier
          unlink($this->tempFilename);
        }
    }

    public function getUploadDir()
    {
        // On retourne le chemin relatif vers l'image pour un navigateur
        return 'uploads/img';
    }

    protected function getUploadRootDir()
    {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }
    
    
     public function getWebPath()
    {
        return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
    }
    
}

src/OC/PlatformBundle/Resources/views/Sidebar/sidebar.html.twig
    {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
        <div class=" user-details">
            <div class="user-image">
                {% if app.user.image %}
                    <img src="{{ asset(app.user.image.webPath) }}" alt="{{ app.user.username }} - avatar" title="{{ app.user.username }}" class="img-circle">
                {% else %}
                    <img src="{{ asset('img/avatar/avatar.jpg') }}" alt="default - avatar" title="{{ app.user.username }}" class="img-circle">
                {% endif %}
            </div>
            <div class="user-info-block">
                <div class="user-heading">
                    <h3>{{ app.user.username }}</h3>
                    <span class="help-block">Chandigarh, IN</span>
                </div>
                <ul class="navigation">
                    <li class="active">
                        <a data-toggle="tab" href="#information">
                            <span class="glyphicon glyphicon-user"></span>
                        </a>
                    </li>
                    <li>
                        <a data-toggle="tab" href="#settings">
                            <span class="glyphicon glyphicon-cog"></span>
                        </a>
                    </li>
                    <li>
                        <a data-toggle="tab" href="#email">
                            <span class="glyphicon glyphicon-envelope"></span>
                        </a>
                    </li>
                    <li>
                        <a data-toggle="tab" href="#events">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </a>
                    </li>
                </ul>
                <div class="user-body">
                    <div class="tab-content">
                        <div id="information" class="tab-pane active">
                            <h4>
                                <a href="{{ path('oc_user_user_cv') }}">
                                    Mes CV
                                </a>
                            </h4>
                        </div>
                        <div id="settings" class="tab-pane">
                            <h4>
                                <a href="{{ path('oc_user_user_show', {id: app.user.id}) }}">
                                    Mon compte
                                </a>
                            </h4>
                            <h4>
                                <a href="{{ path('oc_user_user_edit', {id : app.user.id }) }}">
                                    Editer mon compte
                                </a>
                            </h4>
                            <h4>
                                <a href="{{ path('fos_user_change_password') }}">Changer mon mot de passe</a>
                            </h4>
                        </div>
                        <div id="email" class="tab-pane">
                            <h4>Message</h4>
                        </div>
                        <div id="events" class="tab-pane">
                            <h4>Mes évennements (0)</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <h3>Les annonces</h3>
        <ul class="nav nav-pills nav-stacked">
            <li><a href="{{ path('oc_platform_homepage') }}">Accueil</a></li>
            {# On n'affiche le lien « Ajouter une annonce » qu'aux auteurs
              (et admins, qui héritent du rôle auteur) #}
            {% if is_granted('ROLE_AUTEUR') %}
                <li><a href="{{ path('oc_platform_add') }}">Ajouter une annonce</a></li>
            {% endif %}
        </ul>

        <h4>Dernières annonces</h4>
        {{ render(controller("OCPlatformBundle:Advert:menu", {'limit': 3})) }}
    {% endif %}